"""empty message

Revision ID: 060dc35c7d57
Revises: 8045d6df2a69
Create Date: 2022-04-28 12:46:16.863684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060dc35c7d57'
down_revision = '8045d6df2a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('hair_color', sa.String(length=30), nullable=False),
    sa.Column('eyes_color', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=30), nullable=False),
    sa.Column('terrain', sa.String(length=30), nullable=False),
    sa.Column('gravity', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorito', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('favorito', sa.Column('planeta_id', sa.Integer(), nullable=True))
    op.add_column('favorito', sa.Column('personaje_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorito', 'planeta', ['planeta_id'], ['id'])
    op.create_foreign_key(None, 'favorito', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'favorito', 'personaje', ['personaje_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_column('favorito', 'personaje_id')
    op.drop_column('favorito', 'planeta_id')
    op.drop_column('favorito', 'usuario_id')
    op.drop_table('planeta')
    op.drop_table('personaje')
    # ### end Alembic commands ###
