"""empty message

Revision ID: f183b848d21c
Revises: 060dc35c7d57
Create Date: 2022-04-28 18:46:00.823476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f183b848d21c'
down_revision = '060dc35c7d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fecha_sub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('fecha_sub', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
